# Generated by Django 2.1.2 on 2019-04-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZMoteAPIModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=0)),
                ('sequence', models.TextField(null=True)),
                ('repeat', models.TextField(null=True)),
                ('ZMote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmote', to='ZMoteAPIModule.ZMote')),
            ],
        ),
    ]
