# Generated by Django 2.1.2 on 2019-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZMoteAPIModule', '0002_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, null=True)),
                ('secret', models.CharField(max_length=200, null=True)),
                ('client_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
