# Generated by Django 2.1.2 on 2019-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZMoteAPIModule', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='secret',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
