# Generated by Django 2.1.2 on 2019-03-28 12:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bpmnJson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(null=True)),
                ('appliedMethods', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('appliedConditions', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('appliedPreInputs', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('generatedForms', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='collaborator',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_col', to='APIProjectModule.Workflow'),
        ),
    ]
