# Generated by Django 2.1.2 on 2019-03-12 06:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APIProjectModule', '0002_auto_20190206_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_col', to='APIProjectModule.Workflow'),
        ),
    ]
