# Generated by Django 2.1.2 on 2019-03-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjectModule', '0005_auto_20190314_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='conditions',
            new_name='appliedConditions',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='tasks',
            new_name='appliedMethod',
        ),
    ]
