# Generated by Django 2.1.2 on 2019-03-28 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIProjectModule', '0007_auto_20190326_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='appliedPreInputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
