# Generated by Django 2.1.2 on 2019-04-16 04:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(null=True)),
                ('click_action', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('readFlag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='noti_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
