# Generated by Django 2.1.2 on 2019-04-16 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIRegistrationModule', '0002_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firebase_user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
