# Generated by Django 2.1.2 on 2018-12-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0003_auto_20181205_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecting_method',
            old_name='connecting_service',
            new_name='connecting_method',
        ),
    ]
