# Generated by Django 2.1.2 on 2019-02-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0007_auto_20181217_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='method_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connecting_method',
            name='connecting_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_connecting_service', to='APIModule.Service'),
        ),
        migrations.AlterField(
            model_name='connecting_method',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_main_service', to='APIModule.Method'),
        ),
        migrations.AlterField(
            model_name='method',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='APIModule.Service'),
        ),
    ]
