# Generated by Django 2.1.2 on 2019-04-16 02:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connecting_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(null=True)),
                ('path', models.TextField(null=True)),
                ('method_type', models.TextField(null=True)),
                ('input_interface', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('output_interface', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='APIModule.Service'),
        ),
        migrations.AddField(
            model_name='connecting_method',
            name='connecting_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_connecting_service', to='APIModule.Service'),
        ),
        migrations.AddField(
            model_name='connecting_method',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_main_service', to='APIModule.Method'),
        ),
    ]
