# Generated by Django 2.1.2 on 2019-04-26 03:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(null=True)),
                ('path', models.TextField(null=True)),
                ('method_type', models.TextField(null=True)),
                ('input_interface', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('output_interface', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermethod',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='APIModule.UserService'),
        ),
    ]
