# Generated by Django 2.1.2 on 2019-05-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0002_auto_20190426_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='created',
        ),
    ]
