# Generated by Django 2.1.2 on 2018-12-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0002_auto_20181205_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='connecting_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='connecting_service',
            name='connecting_service',
        ),
        migrations.RemoveField(
            model_name='connecting_service',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='method',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='connecting_service',
        ),
        migrations.AddField(
            model_name='connecting_method',
            name='connecting_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_connecting_service', to='APIModule.service'),
        ),
        migrations.AddField(
            model_name='connecting_method',
            name='method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connecting_method_main_service', to='APIModule.method'),
        ),
    ]
