# Generated by Django 2.1.2 on 2018-12-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIModule', '0005_auto_20181217_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecting_method',
            old_name='method_id',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='method_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='method_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
    ]
